[tox]
min_version = 4.0
env_list =
    lint
    ansible

[testenv:lint]
description = Run YAML and Ansible linting
deps =
    yamllint
    ansible-lint
commands =
    yamllint -s .
    ansible-lint

[testenv:ansible]
description = Run Ansible syntax check and Molecule tests
deps =
    ansible-core>=2.16,<2.17
    molecule
    yamllint
    ansible-lint
commands =
    ansible-playbook --syntax-check playbooks/site.yml -i playbooks/inventory/swift.yml
    molecule test
