---
- name: Site
  hosts: swift
  tasks:
    - name: Deploy and manage Swift cluster
      ansible.builtin.include_role:
        name: csmart.swift.swift
      tags:
        - account
        - common
        - config
        - container
        - disks
        - dispersion
        - hosts
        - keepalived
        - logging
        - memcached
        - object
        - packages
        - prep
        - proxy
        - rings
        - rsyncd
        - selinux
        - services
        - ssl
        - system
        - update
