---
- name: Swift Account Configure
  hosts: swift
  tasks:
    - name: Configure Swift account services
      ansible.builtin.include_role:
        name: csmart.swift.swift
        tasks_from: swift-account-config
